# Generated by Django 2.1.7 on 2019-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('guardian_email', models.CharField(blank=True, max_length=30, null=True)),
                ('guard_name', models.CharField(blank=True, max_length=40, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'guardian',
                'managed': False,
            },
        ),
    ]
