# Generated by Django 2.1.7 on 2019-04-26 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=40)),
                ('stu_gender', models.IntegerField()),
                ('stu_birthday', models.DateField()),
                ('stu_major', models.CharField(max_length=50)),
                ('stu_email', models.CharField(max_length=30)),
                ('stu_c_uni', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StuPhones',
            fields=[
                ('stu_phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stu_phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StuInterests',
            fields=[
                ('stu_interest', models.CharField(max_length=20)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stu.Student')),
            ],
            options={
                'db_table': 'stu_interests',
                'managed': False,
            },
        ),
    ]
