# Generated by Django 2.1.7 on 2019-04-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuApplication',
            fields=[
                ('stu_app_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stu_resume', models.CharField(max_length=100)),
                ('transcript', models.CharField(max_length=100)),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_title', models.CharField(blank=True, max_length=100, null=True)),
                ('conference', models.CharField(blank=True, max_length=50, null=True)),
                ('other_comments', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'stu_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StuDreamMajors',
            fields=[
                ('stu_dream_major', models.CharField(max_length=20)),
                ('stu_app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stu.StuApplication')),
            ],
            options={
                'db_table': 'stu_dream_majors',
                'managed': False,
            },
        ),
    ]
