# Generated by Django 2.1.7 on 2019-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('reg_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reg_password', models.CharField(max_length=16)),
            ],
        ),
    ]
