# Generated by Django 2.1.7 on 2019-04-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20190425_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='reg_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
