# Generated by Django 2.1.7 on 2019-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20190425_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='reg_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='reg_password',
            field=models.CharField(max_length=20),
        ),
    ]
