# Generated by Django 2.1.7 on 2019-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_auto_20190425_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='reg_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='reg_password',
            field=models.CharField(max_length=16),
        ),
    ]
