# Generated by Django 2.1.7 on 2019-04-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('uni_email', models.CharField(max_length=30)),
                ('uni_name', models.CharField(max_length=100)),
                ('uni_phone', models.CharField(max_length=20)),
                ('required_gre_score', models.IntegerField(blank=True, db_column='required_GRE_score', null=True)),
                ('uni_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniOpenMajor',
            fields=[
                ('open_major', models.CharField(max_length=50)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.University')),
            ],
            options={
                'db_table': 'uni_open_major',
                'managed': False,
            },
        ),
    ]
