# Generated by Django 2.1.7 on 2019-04-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreExam',
            fields=[
                ('exam_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('exam_location', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRE_exam',
                'managed': False,
            },
        ),
    ]
