# Generated by Django 2.1.7 on 2019-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('exam_location', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_time', models.DateTimeField(blank=True, null=True)),
                ('availability', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam',
                'managed': False,
            },
        ),
    ]
